# Generated by Django 5.0.4 on 2024-04-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0004_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
