# Generated by Django 5.0.4 on 2024-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0005_remove_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgo',
            name='instruction',
            field=models.CharField(default='', max_length=320),
        ),
    ]
