# Generated by Django 5.0.4 on 2024-04-30 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0006_customgo_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.DateTimeField(blank=True, null=True, verbose_name='assigned')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='completed')),
                ('answer1', models.CharField(default='', max_length=650)),
                ('answer2', models.CharField(default='', max_length=650)),
                ('answer3', models.CharField(default='', max_length=650)),
                ('answer4', models.CharField(default='', max_length=650)),
                ('answer5', models.CharField(default='', max_length=650)),
                ('answer6', models.CharField(default='', max_length=650)),
                ('answer7', models.CharField(default='', max_length=650)),
                ('answer8', models.CharField(default='', max_length=650)),
                ('answer9', models.CharField(default='', max_length=650)),
                ('answer10', models.CharField(default='', max_length=650)),
                ('go_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='coordi.customgo')),
                ('student_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
