# Generated by Django 5.0.4 on 2024-04-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0007_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer10',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer6',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer7',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer8',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='answer9',
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assigned',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='assigned'),
        ),
    ]
