# Generated by Django 5.0.4 on 2024-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0008_remove_assignments_answer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assigned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='assigned'),
        ),
    ]
