# Generated by Django 5.0.4 on 2024-05-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0010_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='assignment_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='coordi.assignments'),
        ),
    ]
