# Generated by Django 5.0.4 on 2024-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0012_alter_data_answer1_alter_data_answer10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='coordi.assignments'),
        ),
    ]
