# Generated by Django 5.0.4 on 2024-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordi', '0014_remove_data_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
